- package:
  - name: taskell
  - section:
    - name: test:taskell-test
    - message:
      - name: Redundant build-depends entry
      - depends: tasty-discover
  - section:
    - name: library
    - message:
      - name: Redundant build-depends entry
      - depends: terminal-size
