name: taskell
version: '1.2.6.0'
category: CLI
author: Mark Wales
maintainer: mark@smallhadroncollider.com
copyright: 2017 Mark Wales
license: BSD3
github: smallhadroncollider/taskell

extra-source-files:
- README.md

default-extensions:
- OverloadedStrings
- NoImplicitPrelude

dependencies:
- classy-prelude

library:
  source-dirs: src
  ghc-options:
  - -O0
  exposed-modules:
  - App
  - Events.State
  - IO.Config
  - IO.Taskell

  # tests
  - Data.Taskell.Date
  - Data.Taskell.List
  - Data.Taskell.List.Internal
  - Data.Taskell.Lists
  - Data.Taskell.Lists.Internal
  - Data.Taskell.Seq
  - Data.Taskell.Subtask
  - Data.Taskell.Subtask.Internal
  - Data.Taskell.Task
  - Data.Taskell.Task.Internal
  - Events.State.Types
  - IO.Markdown.Internal
  - UI.Field

  dependencies:
  - base <=5
  - aeson
  - brick
  - bytestring
  - config-ini
  - containers
  - directory
  - file-embed
  - http-conduit
  - lens
  - mtl
  - text
  - time
  - vty

executables:
  taskell:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - taskell

tests:
  taskell-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - containers
    - lens
    - taskell
    - tasty
    - tasty-discover
    - tasty-expected-failure
    - tasty-hunit
    - text
    - time
