resolver: lts-21.25
compiler: ghc-9.4.8
allow-newer: true
pvp-bounds: lower
packages:
  - .
extra-deps:
  - tz-0.1.3.6
  - brick-0.73




# Original:

# resolver: nightly-2021-07-14
# allow-newer: true
# pvp-bounds: lower
# packages:
#   - .
# extra-deps:
#   - tz-0.1.3.5