name: Build Haskell Project

on:
  push:
    branches:
      - master  # or the branch you want to trigger the build on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Ensure Stack is Installed
      run: |
        if ! command -v stack &> /dev/null
        then
            curl -sSL https://get.haskellstack.org/ | sh
        fi

    - name: Build Project
      run: |
        stack build
        stack install --local-bin-path ./build-output

    - name: Upload Executable
      uses: actions/upload-artifact@v3
      with:
        name: taskell
        path: ./build-output/taskell
