name: Build Taskell Project with Cache

on:
  push:
    branches:
      - master  # Your branch is now "master"

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Restore cache
    - name: Cache Stack build
      uses: actions/cache@v3
      with:
        path: |
          ~/.stack
          .stack-work
        key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml') }}

    - name: Ensure Stack is Installed
      run: |
        if ! command -v stack &> /dev/null
        then
          curl -sSL https://get.haskellstack.org/ | sh
        fi

    - name: Build Taskell Project
      run: |
        stack setup                     # Ensures correct GHC version is installed
        stack build                     # Builds the project using stack.yaml config
        stack install --local-bin-path ./build-output  # Installs the executable in a specified path

    - name: Upload Taskell Executable
      uses: actions/upload-artifact@v4
      with:
        name: taskell-executable
        path: ./build-output/taskell  # The executable file is named "taskell"
